from __future__ import annotations


class ErrorCode:
    BAD_REQUEST = "BAD_REQUEST"
    NOT_FOUND = "NOT_FOUND"
    CONFLICT = "CONFLICT"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    WORKFLOW_INVALID = "WORKFLOW_INVALID"
    WORKFLOW_CANCELLED = "WORKFLOW_CANCELLED"
    DEVICE_ERROR = "DEVICE_ERROR"
    RUN_FAILED = "RUN_FAILED"
    RUN_TIMEOUT = "RUN_TIMEOUT"
    CIRCUIT_OPEN = "CIRCUIT_OPEN"
    DUPLICATE_EXECUTION = "DUPLICATE_EXECUTION"
